d1<- filter(stat_samar, betproblempeople == 1)
dim(d1)
percentage <- dim(d1)/dim(stat_samar)*100
print(percentage)
d2 <- group_by(d1, relatinproblembet)
d3<- table(d1$relatinproblembet)
print(d3)

sportfan<- table(stat_samar$sportfan)
print(sportfan)
dim(stat_samar)
print(sportfan/173*100)
possibility <- table(stat_samar$sportbetpossibly)
print(possibility)
print(possibility/173*100)
sportbet<- table(stat_samar$sportbet)
d4 <- filter(stat_samar, sportfan==4)
print(d4$compsportbet)
mean(d4$compsportbet)
write.table(ds, file = "data.csv", sep = ",",row.names = F)
t1<-table(sports)
library(dplyr)
library(ggplot2)
t2<-data.frame(t1)
write.table(t2, file = "sports.csv", sep = ",",row.names = F)
Belgique <- filter(d, payresidence == "Belgique")
library(pastecs)
stat.desc(d$bettingpercentage)
